version: '3'

tasks:
  update:mas:
    desc: 'List all installed apps from the Mac App Store in nix flake format.'
    cmds:
      - ./mas2nix.py modules/darwin/masApps.nix
  command2package:
    desc: 'Write the command to package mapping to a file.'
    cmds:
      - ./nix_helper.py command2package command2package.csv
  package2command:
    desc: 'Write the package to command mapping to a file.'
    cmds:
      - ./nix_helper.py package2command package2command.yml
