version: '3'

tasks:
  generate:
    desc: "Generate conda environment files."
    cmds:
      - pixi run python -m bsos.conda_web_api generate conda/conda.csv
      - pixi run python -m bsos.conda_web_api generate conda/system.csv -v 3.13 --name-format system --no-python
  clean:
    desc: "Remove the bsos cache when using conda_web_api."
    cmds:
      - pixi run python -m bsos.conda_web_api clean
  list:depended:
    desc: "List all depended packages."
    cmds:
      - |
        < conda/conda.csv tail -n +2 | cut -d, -f6 | tr '/' '\n' | sort -u
